### ISSUE TITLE
Add graylog configurations to transitdata IAC playbooks, configure: 1) input & graylog port to 1514, 2) streams 3) json_parser

### ISSUE THREAD

**Issue by hellej** [HSLdevcom/transitdata#33]

**Comment by kenkus-futurice** [comment]
Check "Graylog configurations" in Evernote:

Backup
Graylog stores UI configs in MongoDB. 
Not tested and not sure if this works because there are auto-generated IDs which may mismatch with other data in MongoDB.
1. ssh to graylog server
2. run `sudo mongodump --db graylog --collection dashboards --collection inputs --collection nodes --collection streams --gzip --archive=graylog-mongodb-configs.gz`
3. this generates a file `graylog-mongodb-configs.gz` which contains the backup data
4. you may need to backup other collections as well in order to make this work

Restore
Again not tested and so on.
1. ssh to graylog server
2. run `sudo mongorestore --gzip --archive=graylog-mongodb-configs.gz to restore from a file graylog-mongodb-configs.gz`
3. please bake into an Ansible playbook if you can make this work
